{"name": "Ошибка при неверном логине", "status": "passed", "description": "Проверка ошибки 404 при несуществующем логине", "steps": [{"name": "Отправка запроса авторизации с неверным логином", "status": "passed", "start": 1752420310796, "stop": 1752420311035}, {"name": "Проверка, что возвращается ошибка 404", "status": "passed", "start": 1752420311036, "stop": 1752420311036}], "start": 1752420310796, "stop": 1752420311036, "uuid": "2d793afc-eb59-4fe1-be80-3488bd268ba2", "historyId": "387c2fbcdbf8bf675812ae422971739c", "testCaseId": "387c2fbcdbf8bf675812ae422971739c", "fullName": "Tests.test_login_courier.TestLoginCourier#test_login_with_error_in_login", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "8088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login_courier"}]}