{"name": "Ошибка при неверном пароле", "status": "passed", "description": "Проверка ошибки 404 при неправильном пароле", "start": 1752323992242, "stop": 1752323992484, "uuid": "b3a3e4cf-3a4d-467e-a70b-133af6ff766f", "historyId": "aa888bf6591480a9eed6507c8477d338", "testCaseId": "aa888bf6591480a9eed6507c8477d338", "fullName": "Tests.test_login_courier.TestLoginCourier#test_login_with_error_in_password", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "80-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login_courier"}]}