{"name": "Ошибка при неверном логине", "status": "passed", "description": "Проверка ошибки 404 при несуществующем логине", "start": 1752323991985, "stop": 1752323992241, "uuid": "640c1d49-c636-419d-be70-199951124380", "historyId": "387c2fbcdbf8bf675812ae422971739c", "testCaseId": "387c2fbcdbf8bf675812ae422971739c", "fullName": "Tests.test_login_courier.TestLoginCourier#test_login_with_error_in_login", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "80-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login_courier"}]}